refactor

diff --git a/.github/workflows/_pypi_upload.yml b/.github/workflows/_pypi_upload.yml
--- a/.github/workflows/_pypi_upload.yml
+++ b/.github/workflows/_pypi_upload.yml
@@ -22,8 +22,8 @@ on:
         default: false
 
 env:
-  gigachain-core: "libs/core"
-  gigachain-community: "libs/community"
+  build-dir-gigachain-core: "libs/core"
+  build-dir-gigachain-community: "libs/community"
 
 jobs:
   check-ci-job-status:
@@ -59,11 +59,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Fail if branch is not main
-        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master'
-        run: |
-          echo "This workflow should not be triggered with workflow_dispatch on a branch other than master"
-          exit 1
+      # - name: Fail if branch is not main
+      #   if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/master'
+      #   run: |
+      #     echo "This workflow should not be triggered with workflow_dispatch on a branch other than master"
+      #     exit 1
       - uses: actions/checkout@v4
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -75,14 +75,14 @@ jobs:
           echo "$HOME/.poetry/bin" >> $GITHUB_PATH
       - name: Build a binary wheel
         run: |
-          cd ${{ env[inputs.distribProjectName] }}
+          cd ${{ env[format('build-dir-{0}',inputs.distribProjectName)] }}
           poetry build
           
       - name: Store the distribution packages
         uses: actions/upload-artifact@v3
         with:
           name: ${{ inputs.distribProjectName }}
-          path: /home/runner/work/gigachain/gigachain/${{ env[inputs.distribProjectName] }}/dist/
+          path: /home/runner/work/gigachain/gigachain/${{ env[format('build-dir-{0}',inputs.distribProjectName)] }}/dist/
   publish-to-pypi:
     if: ${{ inputs.publish }}
     needs:
